version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  # For the API to seed & interact with - there is no direct connection from the UI service
  activities-db:
    image: postgres
    networks:
      - hmpps
    container_name: activities-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=activities-management
      - POSTGRES_USER=activities-management
      - POSTGRES_DB=actvities-management-db

networks:
  hmpps:
