services:

  redis:
    image: 'redis:8.0'
    networks:
      - hmpps
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:6379/health" ]

  hmpps-activities-management-api:
    image: quay.io/hmpps/hmpps-activities-management-api:latest
    networks:
      - hmpps
    container_name: hmpps-activities-management-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal/activities-management-db
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health" ]

  # For the API to seed & interact with - there is no direct connection from the UI service
  activities-db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: activities-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=activities-management
      - POSTGRES_USER=activities-management
      - POSTGRES_DB=activities-management-db
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:5432/health" ]

  # Needed only when running cypress tests
  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: wiremock
    ports:
      - "9091:8080"

networks:
  hmpps:
