/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/video-link-booking/id/{videoBookingId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return the details of a video link booking using its internal ID */
    get: operations['getVideoLinkBookingById']
    /** Endpoint to support the amendment of video link bookings */
    put: operations['amend']
    post?: never
    /** Endpoint to support cancellation of a video booking. */
    delete: operations['cancelVideoBooking']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/video-link-booking': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to support the creation of video link bookings */
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/video-link-booking/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to search for a unique matching video link booking. */
    post: operations['searchForBooking']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/video-link-booking/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to support the request for a prison to create a video link booking for a prisoner due to arrive */
    post: operations['requestBooking']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/probation-teams/user-preferences/set': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to set the probation team preferences for a user (identified from the token content) */
    post: operations['setUserProbationTeamPreferences']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/courts/user-preferences/set': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to set the court preferences for a user (identified from the token content) */
    post: operations['setUserCourtPreferences']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/availability': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Endpoint to assess booking availability and to suggest alternatives */
    post: operations['checkAvailability']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/schedule/probation/{probationTeamCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to retrieve a schedule of bookings for a probation team */
    get: operations['getProbationSchedule']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/schedule/prison/{prisonCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to retrieve a schedule of bookings for a prison */
    get: operations['getScheduleForPrison']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/schedule/court/{courtCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to retrieve a schedule of bookings for a court */
    get: operations['getCourtSchedule']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reference-codes/group/{groupCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return reference data for a provided group key */
    get: operations['getReferenceDataByGroup']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/probation-teams/user-preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return the list of enabled probation teams select by a user (identified from the token content) */
    get: operations['probationTeamsUserPreferences']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/probation-teams/enabled': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return a list of enabled probation teams for video link bookings */
    get: operations['enabledProbationTeams']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/locations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return a list of suitable appointment locations sorted by description at a given prison */
    get: operations['getAppointmentLocationsAtPrison']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return the list of prisons sorted by name known to the service */
    get: operations['prisonsList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/courts/user-preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return the list of enabled courts selected by a user (identified from the token content) */
    get: operations['getUserCourtPreferences']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/courts/enabled': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return a list of enabled courts for video link bookings */
    get: operations['enabledCourts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/booking-contacts/id/{videoBookingId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Endpoint to return a list of contacts associated with a booking */
    get: operations['getContactsForBooking']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description The request with the amended video link booking details */
    AmendVideoBookingRequest: {
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /** @description The prisoner or prisoners associated with the video link booking */
      prisoners: components['schemas']['PrisonerDetails'][]
      /**
       * @description The court code is needed if booking type is COURT, otherwise null
       * @example DRBYMC
       */
      courtCode?: string
      /**
       * @description The court hearing type is needed if booking type is COURT, otherwise null
       * @example APPEAL
       * @enum {string}
       */
      courtHearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * @description The probation team code is needed if booking type is PROBATION, otherwise null
       * @example BLKPPP
       */
      probationTeamCode?: string
      /**
       * @description The probation meeting type is needed if booking type is PROBATION, otherwise null
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description Free text comments for the video link booking
       * @example Waiting to hear on legal representation
       */
      comments?: string
      /**
       * @description The video link for the appointment. Must be a valid URL
       * @example https://video.here.com
       */
      videoLinkUrl?: string
    }
    /** @description
     *           The appointment or appointments associated with the prisoner.
     *
     *           There should only ever be one appointment for a probation meeting.
     *
     *           Court meetings can have up to 3 meetings, a pre, main hearing and post meeting. They must always have a main meeting.
     *
     *           Appointment dates and times must not overlap.
     *          */
    Appointment: {
      /**
       * @description The appointment type
       * @example VLB_COURT_MAIN
       * @enum {string}
       */
      type: 'VLB_PROBATION' | 'VLB_COURT_PRE' | 'VLB_COURT_MAIN' | 'VLB_COURT_POST'
      /**
       * @description The location key for the appointment
       * @example PVI-A-1-001
       */
      locationKey: string
      /**
       * Format: date
       * @description The future date for which the appointment will start
       * @example 2022-12-23
       */
      date: string
      /**
       * Format: partial-time
       * @description Start time for the appointment on the day
       * @example 10:45
       */
      startTime: string
      /**
       * Format: partial-time
       * @description End time for the appointment on the day
       * @example 11:45
       */
      endTime: string
    }
    /** @description The prisoner or prisoners associated with the video link booking */
    PrisonerDetails: {
      /**
       * @description The prison code for the prisoner
       * @example PVI
       */
      prisonCode: string
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /** @description
       *           The appointment or appointments associated with the prisoner.
       *
       *           There should only ever be one appointment for a probation meeting.
       *
       *           Court meetings can have up to 3 meetings, a pre, main hearing and post meeting. They must always have a main meeting.
       *
       *           Appointment dates and times must not overlap.
       *          */
      appointments: components['schemas']['Appointment'][]
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    DlqMessage: {
      body: {
        [key: string]: Record<string, never> | undefined
      }
      messageId: string
    }
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    /** @description The request with the new video link booking details */
    CreateVideoBookingRequest: {
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /** @description The prisoner or prisoners associated with the video link booking */
      prisoners: components['schemas']['PrisonerDetails'][]
      /**
       * @description The court code is needed if booking type is COURT, otherwise null
       * @example DRBYMC
       */
      courtCode?: string
      /**
       * @description The court hearing type is needed if booking type is COURT, otherwise null
       * @example APPEAL
       * @enum {string}
       */
      courtHearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * @description The probation team code is needed if booking type is PROBATION, otherwise null
       * @example BLKPPP
       */
      probationTeamCode?: string
      /**
       * @description The probation meeting type is needed if booking type is PROBATION, otherwise null
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description Free text comments for the video link booking
       * @example Waiting to hear on legal representation
       */
      comments?: string
      /**
       * @description The video link for the appointment. Must be a valid URL
       * @example https://video.here.com
       */
      videoLinkUrl?: string
    }
    /** @description The request with the search criteria for a video booking */
    VideoBookingSearchRequest: {
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description The location key for the appointment
       * @example PVI-A-1-001
       */
      locationKey: string
      /**
       * Format: date
       * @description The date for which the appointment starts
       * @example 2022-12-23
       */
      date: string
      /**
       * Format: partial-time
       * @description Start time for the appointment on the day
       * @example 10:45
       */
      startTime: string
      /**
       * Format: partial-time
       * @description End time for the appointment on the day
       * @example 11:45
       */
      endTime: string
    }
    /** @description A representation of a prison appointment */
    PrisonAppointment: {
      /**
       * Format: int64
       * @description The internal ID for this appointment
       * @example 123
       */
      prisonAppointmentId: number
      /**
       * @description The prison code where this appointment will take place
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The prisoner number for the person attending this appointment
       * @example AA1234A
       */
      prisonerNumber: string
      /**
       * @description The appointment type
       * @example VLB
       */
      appointmentType: string
      /**
       * @description The comments for this appointment
       * @example Please be on time
       */
      comments?: string
      /**
       * @description The location of the appointment at the prison
       * @example VCC-ROOM-1
       */
      prisonLocKey: string
      /**
       * Format: date
       * @description The date of the appointment
       * @example 2024-04-05
       */
      appointmentDate: string
      /**
       * Format: partial-time
       * @description The start time for this appointment
       * @example 11:30
       */
      startTime: string
      /**
       * Format: partial-time
       * @description The end time for this appointment
       * @example 12:30
       */
      endTime: string
    }
    VideoLinkBooking: {
      /**
       * Format: int64
       * @description The internal ID for this booking
       * @example 123
       */
      videoLinkBookingId: number
      /**
       * @description The status of this booking
       * @example ACTIVE
       * @enum {string}
       */
      statusCode: 'ACTIVE' | 'CANCELLED'
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /** @description The prisone appointments related to this booking */
      prisonAppointments: components['schemas']['PrisonAppointment'][]
      /**
       * @description The court code for booking type COURT, otherwise null
       * @example DRBYMC
       */
      courtCode?: string
      /**
       * @description The court description for booking type COURT, otherwise null
       * @example Derby Justice Centre
       */
      courtDescription?: string
      /**
       * @description The court hearing type for booking type COURT, otherwise null
       * @example APPEAL
       * @enum {string}
       */
      courtHearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * @description The court hearing type description, for booking type COURT, otherwise null
       * @example Appeal hearing
       */
      courtHearingTypeDescription?: string
      /**
       * @description The probation team code for booking type PROBATION, otherwise null
       * @example BLKPPP
       */
      probationTeamCode?: string
      /**
       * @description The probation team description for booking type PROBATION, otherwise null
       * @example Barnet PPOC
       */
      probationTeamDescription?: string
      /**
       * @description The probation meeting type for booking type PROBATION, otherwise null
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description The probation meeting type description, required for booking type PROBATION
       * @example Pre-sentence report
       */
      probationMeetingTypeDescription?: string
      /**
       * @description Free text comments for the video link booking
       * @example Waiting to hear on legal representation
       */
      comments?: string
      /**
       * @description The video link for the appointment. Must be a valid URL
       * @example https://video.here.com
       */
      videoLinkUrl?: string
      /**
       * @description True if the booking was made by a prison user.
       * @example false
       */
      createdByPrison?: boolean
      /**
       * @description Username of the person who created this booking.
       * @example creator@email.com
       */
      createdBy: string
      /**
       * Format: date-time
       * @description Date and time it was originally created.
       */
      createdAt: string
      /**
       * @description Username of the person who last amended this booking.
       * @example amender@email.com
       */
      amendedBy?: string
      /**
       * Format: date-time
       * @description Date and time of the last amendment to this booking.
       */
      amendedAt?: string
    }
    /** @description The request with the requested video link booking details */
    RequestVideoBookingRequest: {
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /** @description The prisoner or prisoners associated with the video link booking */
      prisoners: components['schemas']['UnknownPrisonerDetails'][]
      /**
       * @description The court code is needed if booking type is COURT, otherwise null
       * @example DRBYMC
       */
      courtCode?: string
      /**
       * @description The court hearing type is needed if booking type is COURT, otherwise null
       * @example APPEAL
       * @enum {string}
       */
      courtHearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * @description The probation team code is needed if booking type is PROBATION, otherwise null
       * @example BLKPPP
       */
      probationTeamCode?: string
      /**
       * @description The probation meeting type is needed if booking type is PROBATION, otherwise null
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description Free text comments for the video link booking
       * @example Waiting to hear on legal representation
       */
      comments?: string
      /**
       * @description The video link for the appointment. Must be a valid URL
       * @example https://video.here.com
       */
      videoLinkUrl?: string
    }
    /** @description The prisoner or prisoners associated with the video link booking */
    UnknownPrisonerDetails: {
      /**
       * @description The prison code for the prison which the prisoner is due to arrive
       * @example PVI
       */
      prisonCode: string
      /**
       * @description The prisoner's first name
       * @example Joe
       */
      firstName: string
      /**
       * @description The prisoner's last name
       * @example Bloggs
       */
      lastName: string
      /**
       * Format: date
       * @description The prisoner's date of birth
       * @example 1970-01-01
       */
      dateOfBirth: string
      /** @description
       *           The appointment or appointments associated with the prisoner.
       *
       *           There should only ever be one appointment for a probation meeting.
       *
       *           Court meetings can have up to 3 meetings, a pre, main hearing and post meeting. They must always have a main meeting.
       *
       *           Appointment dates and times must not overlap.
       *          */
      appointments: components['schemas']['Appointment'][]
    }
    /** @description The request body containing the user probation team preferences */
    SetProbationTeamPreferencesRequest: {
      /** @description The list of probation team codes to set as the preferences for this username. */
      probationTeamCodes: string[]
    }
    /** @description Describes the response from setting the user probation team preferences */
    SetProbationTeamPreferencesResponse: {
      /**
       * Format: int32
       * @description The count of probation teams saved as preferences for this user
       */
      probationTeamsSaved: number
    }
    /** @description The request body containing the user court preferences */
    SetCourtPreferencesRequest: {
      /** @description The list of court codes to set as the preferences for this username. */
      courtCodes: string[]
    }
    /** @description Describes the response from setting the user court preferences */
    SetCourtPreferencesResponse: {
      /**
       * Format: int32
       * @description The count of courts saved as preferences for this user
       */
      courtsSaved: number
    }
    /** @description The request containing the times and locations of hearings to check for availability */
    AvailabilityRequest: {
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /**
       * @description The court code or probation team code
       * @example DRBYMC
       */
      courtOrProbationCode: string
      /**
       * @description The prison code where these appointment will take place
       * @example MDI
       */
      prisonCode: string
      /**
       * Format: date
       * @description The date for the appointments on this booking (must all be on the same day)
       * @example 2024-04-05
       */
      date: string
      preAppointment?: components['schemas']['LocationAndInterval']
      mainAppointment: components['schemas']['LocationAndInterval']
      postAppointment?: components['schemas']['LocationAndInterval']
      /**
       * Format: int64
       * @description Exclude the video link booking with this ID from the availability check. Useful when checking availability during the amending of a booking.
       */
      vlbIdToExclude?: number
    }
    /** @description A time interval between a start and end time */
    Interval: {
      /**
       * Format: partial-time
       * @description The interval start time, inclusive. ISO-8601 format (hh:mm)
       * @example 09:00
       */
      start: string
      /**
       * Format: partial-time
       * @description The interval end time (inclusive). ISO-8601 format (hh:mm)
       * @example 09:30
       */
      end: string
    }
    /** @description The prison location key and start/end interval for an appointment slot */
    LocationAndInterval: {
      /**
       * @description The location of the appointment at the prison
       * @example VCC-ROOM-1
       */
      prisonLocKey: string
      interval?: components['schemas']['Interval']
    }
    /** @description Availability check response */
    AvailabilityResponse: {
      /**
       * @description Set to true when all the locations and times for this booking are available, or false when not.
       * @example true
       */
      availabilityOk: boolean
      /** @description A list of alternative times and locations for the requested appointment on this booking, or empty list */
      alternatives: components['schemas']['BookingOption'][]
    }
    /** @description Video link booking option */
    BookingOption: {
      pre?: components['schemas']['LocationAndInterval']
      main: components['schemas']['LocationAndInterval']
      post?: components['schemas']['LocationAndInterval']
    }
    /** @description An item on a schedule i.e. prison appointments and their booking details */
    ScheduleItem: {
      /**
       * Format: int64
       * @description The internal ID for the video booking
       * @example 123
       */
      videoBookingId: number
      /**
       * Format: int64
       * @description The internal ID for an appointment related to a booking. It is unique in this list
       * @example 123
       */
      prisonAppointmentId: number
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /**
       * @description The booking status
       * @example ACTIVE
       * @enum {string}
       */
      statusCode: 'ACTIVE' | 'CANCELLED' | 'ACTIVE' | 'CANCELLED'
      /**
       * @description The video link URL to attend this event
       * @example https://video.link.url
       */
      videoUrl?: string
      /**
       * @description The comments provided for the booking
       * @example Free text comment
       */
      bookingComments?: string
      /**
       * @description True if the booking was made by a prison user
       * @example false
       * @enum {boolean}
       */
      createdByPrison: true | false
      /**
       * Format: int64
       * @description The internal court ID, if this is a court booking
       * @example 1234
       */
      courtId?: number
      /**
       * @description The court code, if this is a court booking
       * @example DRBYMC
       */
      courtCode?: string
      /**
       * @description The court description, if this is a court booking
       * @example Derby Magistrates
       */
      courtDescription?: string
      /**
       * @description The court hearing type code, if this is a court booking
       * @example APPEAL
       * @enum {string}
       */
      hearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * @description The court hearing type description, if this is a court booking
       * @example Appeal hearing
       */
      hearingTypeDescription?: string
      /**
       * Format: int64
       * @description The internal probation team ID, if this is a probation booking
       * @example 1234
       */
      probationTeamId?: number
      /**
       * @description The internal probation team code, if this is a probation booking
       * @example BLCKPPP
       */
      probationTeamCode?: string
      /**
       * @description The probation team description, if this is a probation booking
       * @example Blackpool PP
       */
      probationTeamDescription?: string
      /**
       * @description The probation meeting type code, if this is a probation booking
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description The probation meeting type description, if this is a probation booking
       * @example Pre-sentence report
       */
      probationMeetingTypeDescription?: string
      /**
       * @description The prison code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The prison name
       * @example HMP Moorland
       */
      prisonName: string
      /**
       * @description The prisoner number (NOMS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description The appointment type
       * @example 1234
       * @enum {string}
       */
      appointmentType: 'VLB_PROBATION' | 'VLB_COURT_PRE' | 'VLB_COURT_MAIN' | 'VLB_COURT_POST'
      /**
       * @description The appointment type description
       * @example Court - main hearing
       */
      appointmentTypeDescription?: string
      /**
       * @description The appointment comments
       * @example This is a free text comment
       */
      appointmentComments?: string
      /**
       * @description The location key for the room where the appointment will take place in the prison.
       * @example MDI-VCC-1
       */
      prisonLocKey: string
      /**
       * Format: date
       * @description The date for this appointment ISO format (YYYY-MM-DD)
       * @example 2024-10-03
       */
      appointmentDate: string
      /**
       * Format: partial-time
       * @description The start time for the appointment ISO time format (HH:MI)
       * @example 12:45
       */
      startTime: string
      /**
       * Format: partial-time
       * @description The end time for the appointment ISO time format (HH:MI)
       * @example 13:15
       */
      endTime: string
    }
    /** @description Describes the details of a reference code */
    ReferenceCode: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this reference code.
       * @example 12345
       */
      referenceCodeId: number
      /**
       * @description The group name for related reference codes.
       * @example COURT_HEARING_TYPE
       */
      groupCode: string
      /**
       * @description The code for this reference data
       * @example SEN
       */
      code: string
      /**
       * @description A fuller description of the reference code
       * @example Sentencing hearing
       */
      description?: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    /** @description Describes the details of a probation team */
    ProbationTeam: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this probation team.
       * @example 12345
       */
      probationTeamId: number
      /**
       * @description A short code for this probation team.
       * @example NORTHWEST-PCC
       */
      code: string
      /**
       * @description A fuller description for this probation team
       * @example North West Primary Care
       */
      description: string
      /**
       * @description A boolean value to show whether enabled for video link bookings.
       * @example true
       */
      enabled: boolean
      /**
       * @description Notes relating to this probation team for opening hours, postal address, main contact.
       * @example Free form notes
       */
      notes?: string
    }
    Location: {
      /**
       * @description The unique location key for the location
       * @example BMI-VIDEOLINK
       */
      key: string
      /**
       * @description The description for the location, can be null
       * @example VIDEO LINK
       */
      description?: string
      /**
       * @description Flag indicates if the location is enabled, true is enabled and false is disabled.
       * @example true
       */
      enabled: boolean
    }
    /** @description Describes the details of a prison */
    Prison: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this prison.
       * @example 12345
       */
      prisonId: number
      /**
       * @description A short code for this prison.
       * @example BMI
       */
      code: string
      /**
       * @description A fuller description for this prison
       * @example HMP Birmingham
       */
      name: string
      /**
       * @description A boolean value to show whether the prison is enabled for self-service video link bookings by court/probation.
       * @example true
       */
      enabled: boolean
      /**
       * @description Notes relating to this prison, e.g. number of video-enabled rooms, address.
       * @example Free form notes
       */
      notes?: string
    }
    /** @description Describes the details of a court */
    Court: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this court.
       * @example 12345
       */
      courtId: number
      /**
       * @description A short code for this court.
       * @example AVONCC
       */
      code: string
      /**
       * @description A fuller description for this court
       * @example Avon Crown Court
       */
      description: string
      /**
       * @description A boolean value to show whether enabled for video link bookings.
       * @example true
       */
      enabled: boolean
      /**
       * @description Notes relating to this court for opening hours, postal address, main contact.
       * @example Free form notes
       */
      notes?: string
    }
    /** @description Describes the details of a booking contact */
    BookingContact: {
      /**
       * Format: int64
       * @description Describes the internal id of the video booking
       * @example 123
       */
      videoBookingId: number
      /**
       * @description Describes the contact type
       * @example PRISON
       * @enum {string}
       */
      contactType: 'USER' | 'COURT' | 'PROBATION' | 'PRISON' | 'THIRD_PARTY'
      /**
       * @description Describes the contact name (optional)
       * @example Mr. Person-contact
       */
      name?: string
      /**
       * @description Describes the position or role of the contact person (optional)
       * @example BVLS Administrator
       */
      position?: string
      /**
       * @description Describes the email address of this contact (optional)
       * @example example@example.com
       */
      email?: string
      /**
       * @description Describes the telephone number of this contact (optional)
       * @example 00902 0909779
       */
      telephone?: string
      /**
       * @description
       *         Describes the whether the contact is a primary contact or not, true if yes otherwise false.
       *
       *         There will only ever be one primary contact for each contact type e.g. a court will only have one primary contact.
       *
       * @example true
       */
      primaryContact: boolean
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getVideoLinkBookingById: {
    parameters: {
      query?: never
      header?: never
      path: {
        videoBookingId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Video link booking details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VideoLinkBooking']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The video booking ID was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  amend: {
    parameters: {
      query?: never
      header?: never
      path: {
        videoBookingId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AmendVideoBookingRequest']
      }
    }
    responses: {
      /** @description The unique identifier of the video booking */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': number
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The video booking ID was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  cancelVideoBooking: {
    parameters: {
      query?: never
      header?: never
      path: {
        videoBookingId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Video booking was cancelled. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The video booking ID was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVideoBookingRequest']
      }
    }
    responses: {
      /** @description The unique identifier of the created video booking */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': number
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchForBooking: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VideoBookingSearchRequest']
      }
    }
    responses: {
      /** @description The matching video link booking details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VideoLinkBooking']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  requestBooking: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestVideoBookingRequest']
      }
    }
    responses: {
      /** @description The video link booking has been requested */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  setUserProbationTeamPreferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetProbationTeamPreferencesRequest']
      }
    }
    responses: {
      /** @description Count of the number of probation teams saved in this request */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SetProbationTeamPreferencesResponse']
        }
      }
      /** @description Invalid request provided */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  setUserCourtPreferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetCourtPreferencesRequest']
      }
    }
    responses: {
      /** @description Count of the number of courts saved in this request */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SetCourtPreferencesResponse']
        }
      }
      /** @description Invalid request provided */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  checkAvailability: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AvailabilityRequest']
      }
    }
    responses: {
      /** @description Availability response, including any suggested alternative booking options */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AvailabilityResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getProbationSchedule: {
    parameters: {
      query?: {
        /** @description A date in ISO format (YYYY-MM-DD). Defaults to today if not supplied. */
        date?: string
        /** @description Include cancelled bookings (true or false), defaults to false. */
        includeCancelled?: boolean
      }
      header?: never
      path: {
        /** @description A probation team code */
        probationTeamCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of scheduled video link appointments and booking details for one probation team */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScheduleItem'][]
        }
      }
      /** @description Bad request. Message contains the detail. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getScheduleForPrison: {
    parameters: {
      query?: {
        /** @description A date in ISO format (YYYY-MM-DD). Defaults to today if not supplied. */
        date?: string
        /** @description Include cancelled bookings (true or false), defaults to false. */
        includeCancelled?: boolean
      }
      header?: never
      path: {
        /** @description A prison code */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of scheduled video link appointments and booking details at the prison. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScheduleItem'][]
        }
      }
      /** @description Bad request. Message contains the detail. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getCourtSchedule: {
    parameters: {
      query?: {
        /** @description A date in ISO format (YYYY-MM-DD). Defaults to today if not supplied. */
        date?: string
        /** @description Include cancelled bookings (true or false), defaults to false. */
        includeCancelled?: boolean
      }
      header?: never
      path: {
        /** @description A court code */
        courtCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of scheduled video link appointments and booking details for one court */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScheduleItem'][]
        }
      }
      /** @description Bad request. Message contains the detail. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getReferenceDataByGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description EnabledOnly true or false. Defaults to false if not supplied. */
        groupCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of reference data codes/values */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferenceCode'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  probationTeamsUserPreferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Probation teams select by this user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProbationTeam'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  enabledProbationTeams: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Probation teams */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProbationTeam'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAppointmentLocationsAtPrison: {
    parameters: {
      query?: {
        /** @description Enabled (active) locations only, true or false. Defaults to true if not supplied. */
        enabledOnly?: boolean
        /** @description Video link only, true or false. When true only returns video link suitable locations. Defaults to true if not supplied. */
        videoLinkOnly?: boolean
      }
      header?: never
      path: {
        /** @description The prison code for which locations will be retrieved. */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Locations */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Location'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  prisonsList: {
    parameters: {
      query?: {
        /** @description EnabledOnly true or false. Defaults to false if not supplied. */
        enabledOnly?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of prisons */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Prison'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getUserCourtPreferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Courts selected by this user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Court'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  enabledCourts: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Courts */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Court'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getContactsForBooking: {
    parameters: {
      query?: never
      header?: never
      path: {
        videoBookingId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Contacts for this booking */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BookingContact'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The video booking ID was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
