export default {
  activities: [
    {
      path: 'waitlist-agg',
      title: 'Waitlist Aggregate Report',
      definitionName: 'waitlist-list-001',
      variantName: 'waitlist-aggregate-001',
      displayTitle: 'Waitlist aggregation with averages',
      displayDescription: 'Some description of the report',
      roleRequired: true,
      category: 'waitlists',
    },
    {
      path: 'purposeful-residential',
      title: 'PA sessions residential',
      definitionName: 'pa-residential-001',
      variantName: 'pa-residential-week-001',
      displayTitle: 'PA sessions week-to-date by residential',
      displayDescription: 'Some description of the report',
      roleRequired: true,
      category: 'purposeful-activity',
    },
    {
      path: 'attendance-time',
      title: 'Attendance vs time',
      definitionName: 'attendance-vs-time-001',
      variantName: 'attendance-vs-time-001',
      displayTitle: 'Activity attendance across time',
      displayDescription: 'Some description of the report',
      roleRequired: true,
      category: 'attendance',
    },
    {
      path: 'month-kpi',
      title: 'Monthly KPI dash',
      definitionName: 'kpi-monthly-dash-001',
      variantName: 'kpi-monthly-dash-001',
      displayTitle: 'Month vs Month KPI dashboard',
      displayDescription: 'Some description of the report',
      roleRequired: true,
      category: 'kpi',
    },
  ],
  appointments: [
    {
      path: 'appointment-attendance-dates',
      title: 'Attendance between 2 dates',
      definitionName: 'test-list-001',
      variantName: 'test-attendance-two-dates-001',
      displayTitle: 'Attendance between 2 dates',
      displayDescription:
        'Get attendance information for all appointments that took place between 2 dates, to check attendance levels over time.',
      roleRequired: true,
    },
  ],
}
