import { components } from '.'

export type CaseLoad = components['schemas']['CaseLoad']
export type InmateDetail = components['schemas']['InmateDetail']
export type PrisonApiUserDetail = components['schemas']['UserDetail']
export type Location = components['schemas']['Location']
export type PrisonerSchedule = components['schemas']['PrisonerSchedule']
export type ScheduledAppointmentDto = components['schemas']['ScheduledAppointmentDto']
export type ScheduledEvent = components['schemas']['ScheduledEvent']
export type CourtEvent = components['schemas']['CourtEvent']
export type Assessment = components['schemas']['Assessment']
export type OffenderSentenceDetail = components['schemas']['OffenderSentenceDetail']
export type SentenceCalcDates = components['schemas']['SentenceCalcDates']
export type TransferEvent = components['schemas']['TransferEvent']
export type Alert = components['schemas']['Alert']
export type AlertV1 = components['schemas']['AlertV1']
