import getInmateDetails from '../../fixtures/prisonerSearchApi/getPrisoner-MDI-A5015DY.json'
import exclusionsViewAllocations from '../../pages/activities/exclusionsViewAllocations'
import ViewSuspensionPage from '../../pages/activities/suspensions/viewSuspension'
import Page from '../../pages/page'

const getPrisonerAllocations = [
  {
    prisonerNumber: 'A5015DY',
    allocations: [
      {
        id: 1,
        activitySummary: 'Entry level Maths 1',
        activityId: 1,
        scheduleId: 1,
        scheduleDescription: 'Entry level Maths 1',
        status: 'SUSPENDED',
        plannedSuspension: {
          plannedStartDate: '2024-12-13',
          plannedEndDate: null,
          caseNoteId: null,
          dpsCaseNoteId: null,
          plannedBy: 'USER1',
          plannedAt: '2024-12-13T14:40:02.594376',
          paid: true,
        },
        exclusions: [{ weekNumber: 1, timeSlot: 'AM', monday: true, daysOfWeek: ['MONDAY'] }],
      },
    ],
  },
  {
    prisonerNumber: 'A5015DY',
    allocations: [
      {
        id: 2,
        activitySummary: 'Gym',
        activityId: 2,
        scheduleId: 2,
        scheduleDescription: 'Gym',
        status: 'SUSPENDED_WITH_PAY',
        plannedSuspension: {
          plannedStartDate: '2024-12-13',
          plannedEndDate: null,
          caseNoteId: null,
          dpsCaseNoteId: null,
          plannedBy: 'USER1',
          plannedAt: '2024-12-13T14:40:02.594376',
          paid: true,
        },
        exclusions: [{ weekNumber: 1, timeSlot: 'AM', monday: true, daysOfWeek: ['MONDAY', 'WEDNESDAY'] }],
      },
    ],
  },
  {
    prisonerNumber: 'A5015DY',
    allocations: [
      {
        id: 3,
        activitySummary: 'CIT Plastering',
        activityId: 3,
        scheduleId: 3,
        scheduleDescription: 'CIT Plastering',
        status: 'ACTIVE',
        exclusions: [{ weekNumber: 1, timeSlot: 'AM', monday: true, daysOfWeek: ['SUNDAY'] }],
      },
    ],
  },
]

const getSchedules = {
  id: 1,
  instances: [
    {
      id: 1,
      date: '10/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 2,
      date: '17/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 3,
      date: '24/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 4,
      date: '31/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 5,
      date: '07/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 6,
      date: '14/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 7,
      date: '21/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 8,
      date: '28/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 9,
      date: '05/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 10,
      date: '12/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 11,
      date: '19/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
  ],
  allocations: [
    {
      id: 1,
      prisonerNumber: 'A5015DY',
      activitySummary: 'Maths level 1',
      scheduleId: 1,
      scheduleDescription: 'Entry level Maths 1',
      incentiveLevel: 'BAS',
      prisonPayBand: {
        id: 1,
        displaySequence: 1,
        alias: 'A',
        description: 'A',
        nomisPayBand: 1,
        prisonCode: 'PVI',
      },
      startDate: '2022-10-10',
      endDate: null,
      status: 'SUSPENDED',
      allocatedTime: '10/10/2022 09:30',
      allocatedBy: 'MR BLOGS',
      deallocatedTime: null,
      deallocatedBy: null,
      deallocatedReason: null,
    },
  ],
  description: 'Entry level Maths 1',
  suspensions: [],
  internalLocation: {
    id: 1,
    code: 'EDU-ROOM-1',
    description: 'Education - R1',
  },
  capacity: 10,
  activity: {
    id: 1,
    prisonCode: 'MDI',
    attendanceRequired: true,
    inCell: false,
    pieceWork: false,
    outsideWork: false,
    payPerSession: 'H',
    summary: 'Maths level 1',
    description: 'A basic maths course suitable for introduction to the subject',
    category: {
      id: 1,
      code: 'EDU',
      name: 'Education',
      description: 'Such as classes in English, maths, construction and computer skills',
    },
    paid: true,
  },
  startDate: '2022-08-01',
  endDate: '2024-08-01',
  scheduleWeeks: 1,
  slots: [
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Mon'],
      mondayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Tue'],
      tuesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Wed'],
      wednesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Thu'],
      thursdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Fri'],
      fridayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sat'],
      saturdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sun'],
      sundayFlag: true,
      timeSlot: 'AM',
    },
  ],
  runsOnBankHoliday: false,
  usePrisonRegimeTime: true,
} as unknown as JSON

const getSchedules2 = {
  id: 2,
  instances: [
    {
      id: 1,
      date: '10/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 2,
      date: '17/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 3,
      date: '24/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 4,
      date: '31/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 5,
      date: '07/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 6,
      date: '14/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 7,
      date: '21/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 8,
      date: '28/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 9,
      date: '05/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 10,
      date: '12/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 11,
      date: '19/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
  ],
  allocations: [
    {
      id: 2,
      prisonerNumber: 'A5015DY',
      activitySummary: 'Gym',
      scheduleId: 1,
      scheduleDescription: 'Gym',
      incentiveLevel: 'BAS',
      prisonPayBand: {
        id: 1,
        displaySequence: 1,
        alias: 'A',
        description: 'A',
        nomisPayBand: 1,
        prisonCode: 'PVI',
      },
      startDate: '2022-10-10',
      endDate: null,
      status: 'SUSPENDED_WITH_PAY',
      allocatedTime: '10/10/2022 09:30',
      allocatedBy: 'MR BLOGS',
      deallocatedTime: null,
      deallocatedBy: null,
      deallocatedReason: null,
    },
  ],
  description: 'Gym',
  suspensions: [],
  internalLocation: {
    id: 1,
    code: 'EDU-ROOM-1',
    description: 'Education - R1',
  },
  capacity: 10,
  activity: {
    id: 3,
    prisonCode: 'MDI',
    attendanceRequired: true,
    inCell: false,
    pieceWork: false,
    outsideWork: false,
    payPerSession: 'H',
    summary: 'Maths level 1',
    description: 'A basic maths course suitable for introduction to the subject',
    category: {
      id: 1,
      code: 'EDU',
      name: 'Education',
      description: 'Such as classes in English, maths, construction and computer skills',
    },
    paid: true,
  },
  startDate: '2022-08-01',
  endDate: '2024-08-01',
  scheduleWeeks: 1,
  slots: [
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Mon'],
      mondayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Tue'],
      tuesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Wed'],
      wednesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Thu'],
      thursdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Fri'],
      fridayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sat'],
      saturdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sun'],
      sundayFlag: true,
      timeSlot: 'AM',
    },
  ],
  runsOnBankHoliday: false,
  usePrisonRegimeTime: true,
} as unknown as JSON

const getSchedules3 = {
  id: 3,
  instances: [
    {
      id: 1,
      date: '10/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 2,
      date: '17/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 3,
      date: '24/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 4,
      date: '31/10/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 5,
      date: '07/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 6,
      date: '14/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 7,
      date: '21/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 8,
      date: '28/11/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 9,
      date: '05/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 10,
      date: '12/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
    {
      id: 11,
      date: '19/12/2022',
      startTime: '10:00',
      endTime: '11:00',
      cancelled: false,
      cancelledTime: null,
      cancelledBy: null,
      attendances: [],
      timeSlot: 'AM',
    },
  ],
  allocations: [
    {
      id: 3,
      prisonerNumber: 'A5015DY',
      activitySummary: 'CIT Plastering',
      scheduleId: 1,
      scheduleDescription: 'CIT Plastering',
      incentiveLevel: 'BAS',
      prisonPayBand: {
        id: 1,
        displaySequence: 1,
        alias: 'A',
        description: 'A',
        nomisPayBand: 1,
        prisonCode: 'PVI',
      },
      startDate: '2022-10-10',
      endDate: null,
      status: 'ACTIVE',
      allocatedTime: '10/10/2022 09:30',
      allocatedBy: 'MR BLOGS',
      deallocatedTime: null,
      deallocatedBy: null,
      deallocatedReason: null,
    },
  ],
  description: 'CIT Plastering',
  suspensions: [],
  internalLocation: {
    id: 1,
    code: 'EDU-ROOM-1',
    description: 'Education - R1',
  },
  capacity: 10,
  activity: {
    id: 3,
    prisonCode: 'MDI',
    attendanceRequired: true,
    inCell: false,
    pieceWork: false,
    outsideWork: false,
    payPerSession: 'H',
    summary: 'Maths level 1',
    description: 'A basic maths course suitable for introduction to the subject',
    category: {
      id: 1,
      code: 'EDU',
      name: 'Education',
      description: 'Such as classes in English, maths, construction and computer skills',
    },
    paid: true,
  },
  startDate: '2022-08-01',
  endDate: '2024-08-01',
  scheduleWeeks: 1,
  slots: [
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Mon'],
      mondayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Tue'],
      tuesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '10:00',
      endTime: '11:00',
      daysOfWeek: ['Wed'],
      wednesdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Thu'],
      thursdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Fri'],
      fridayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sat'],
      saturdayFlag: true,
      timeSlot: 'AM',
    },
    {
      id: 1,
      weekNumber: 1,
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: ['Sun'],
      sundayFlag: true,
      timeSlot: 'AM',
    },
  ],
  runsOnBankHoliday: false,
  usePrisonRegimeTime: true,
} as unknown as JSON

context('Exclusions', () => {
  beforeEach(() => {
    cy.task('reset')
    cy.task('stubSignIn')
    cy.stubEndpoint('GET', '/prisoner/A5015DY', getInmateDetails)
    cy.stubEndpoint('POST', '/prisons/MDI/prisoner-allocations', getPrisonerAllocations)
    cy.stubEndpoint('GET', '/schedules/1', getSchedules)
    cy.stubEndpoint('GET', '/schedules/2', getSchedules2)
    cy.stubEndpoint('GET', '/schedules/3', getSchedules3)

    cy.signIn()
  })
  it('should render the exclusions allocation page', () => {
    cy.visit('/activities/exclusions/prisoner/A5015DY')

    const exclusionsAllocationsPage = Page.verifyOnPage(exclusionsViewAllocations)
    exclusionsAllocationsPage.viewSuspendedLinks().should('have.lengthOf', 2)
  })

  it('should take you to the manage suspension page', () => {
    cy.visit('/activities/exclusions/prisoner/A5015DY')

    const exclusionsAllocationsPage = Page.verifyOnPage(exclusionsViewAllocations)
    exclusionsAllocationsPage.viewSuspendedLinks().should('have.lengthOf', 2).invoke('removeAttr', 'target')
    exclusionsAllocationsPage.firstSuspensionLink()

    const viewSuspensionPage = Page.verifyOnPage(ViewSuspensionPage)
    viewSuspensionPage
      .summary()
      .find('dt')
      .then($dt => {
        expect($dt.get(0).innerText).to.contain('Activity')
        expect($dt.get(1).innerText).to.contain('First day of suspension')
        expect($dt.get(2).innerText).to.contain('Last day of suspension')
        expect($dt.get(3).innerText).to.contain('Paid while suspended?')
        expect($dt.get(4).innerText).to.contain('Added by')
      })
    viewSuspensionPage
      .summary()
      .find('dd')
      .then($dd => {
        expect($dd.get(0).innerText).to.contain('Entry level Maths 1')
        expect($dd.get(1).innerText).to.contain('Friday, 13 December 2024')
        expect($dd.get(2).innerText).to.contain('No end date')
        expect($dd.get(3).innerText).to.contain('Yes')
      })
  })
})
