enum AttendanceReason {
  SICK = 'SICK',
  REFUSED = 'REFUSED',
  NOT_REQUIRED = 'NOT_REQUIRED',
  REST = 'REST',
  CLASH = 'CLASH',
  OTHER = 'OTHER',
  AUTO_SUSPENDED = 'AUTO_SUSPENDED',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  ATTENDED = 'ATTENDED',
}

export default AttendanceReason
