/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/queue-admin/retry-dlq/{dlqName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["retryDlq"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue-admin/retry-all-dlqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["retryAllDlqs"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue-admin/purge-queue/{queueName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["purgeQueue"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Re-open a non-association
         * @description Requires REOPEN_NON_ASSOCIATIONS role with write scope.
         *     **Please note**: This is a special endpoint which should NOT be exposed to regular users, they should instead create a new non-association.
         */
        put: operations["reopenNonAssociation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Close a non-association
         * @description Requires WRITE_NON_ASSOCIATIONS role with write scope.
         */
        put: operations["closeNonAssociation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get non-associations, filtered and paged
         * @description Requires READ_NON_ASSOCIATIONS role
         */
        get: operations["getNonAssociations"];
        put?: never;
        /**
         * Creates a non-association between two prisoners.
         * @description Requires WRITE_NON_ASSOCIATIONS role with write scope.
         */
        post: operations["createNonAssociation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a non-association
         * @description Requires DELETE_NON_ASSOCIATIONS role with write scope.
         *     **Please note**: This is a special endpoint which should NOT be exposed to regular users, they should instead close non-associations.
         */
        post: operations["deleteNonAssociation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/involving": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get non-associations involving any of the given prisoners. Either person in the non-association must be in the provided list.
         * @description Requires READ_NON_ASSOCIATIONS role.
         */
        post: operations["getNonAssociationsInvolvingPrisoners"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/between": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get non-associations between two or more prisoners by prisoner number. Both people in the non-associations must be in the provided list.
         * @description Requires READ_NON_ASSOCIATIONS role.
         */
        post: operations["getNonAssociationsBetweenPrisoners"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/non-associations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a non-association between two prisoners by ID.
         * @description Requires READ_NON_ASSOCIATIONS role.
         */
        get: operations["getNonAssociation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partial update of a non-association by ID.
         * @description Requires WRITE_NON_ASSOCIATIONS role with write scope.
         */
        patch: operations["patchNonAssociation"];
        trace?: never;
    };
    "/subject-access-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
         * @description Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
         */
        get: operations["getSarContentByReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue-admin/get-dlq-messages/{dlqName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDlqMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prisoner/{prisonerNumber}/non-associations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get non-associations by prisoner number
         * @description Requires READ_NON_ASSOCIATIONS role.
         */
        get: operations["getPrisonerNonAssociations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/api/non-associations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a non-association between two prisoners by ID in NOMIS/Prison API format
         * @description Requires NON_ASSOCIATIONS_SYNC role.
         */
        get: operations["getLegacyById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List codes and descriptions for enumerated field types */
        get: operations["constants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RetryDlqResult: {
            /** Format: int32 */
            messagesFoundCount: number;
        };
        PurgeQueueResult: {
            /** Format: int32 */
            messagesFoundCount: number;
        };
        /** @description Error response */
        ErrorResponse: {
            /**
             * Format: int32
             * @description HTTP status code
             * @example 500
             */
            status: number;
            /**
             * @description User message for the error
             * @example No non-association found for ID `324234`
             */
            userMessage: string;
            /**
             * @description More detailed error message
             * @example [Details, sometimes a stack trace]
             */
            developerMessage: string;
            /**
             * Format: int32
             * @description When present, uniquely identifies the type of error making it easier for clients to discriminate without relying on error description or HTTP status code; see `uk.gov.justice.digital.hmpps.hmppsnonassociationsapi.config.ErrorCode` enumeration in hmpps-non-associations-api
             * @example 101
             */
            errorCode?: number | null;
            /**
             * @description More information about the error
             * @example [Rarely used, error-specific]
             */
            moreInfo?: string | null;
        };
        /** @description Request to re-open a non-association */
        ReopenNonAssociationRequest: {
            /**
             * @description Reason for re-opening the non-association
             * @example Prisoners are fighting again
             */
            reopenReason: string;
            /**
             * Format: date-time
             * @description Date and time of the re-open, if not provided will default to today's time
             * @default now
             * @example 2023-06-07T10:30:00
             */
            reopenedAt: string | null;
            /**
             * @description The username of the member of staff requesting the re-open, if not provided will use the user in the JWT access token
             * @example AJONES
             */
            reopenedBy: string | null;
        };
        /** @description Non-association */
        NonAssociation: {
            /**
             * Format: int64
             * @description ID of the non-association
             * @example 42
             */
            id: number;
            /**
             * @description Prisoner number to not associate
             * @example A1234BC
             */
            firstPrisonerNumber: string;
            /**
             * @description This prisoner’s role code in the non-association
             * @example VICTIM
             * @enum {string}
             */
            firstPrisonerRole: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description This prisoner’s role description in the non-association
             * @example Victim
             */
            firstPrisonerRoleDescription: string;
            /**
             * @description Prisoner number to not associate
             * @example D5678EF
             */
            secondPrisonerNumber: string;
            /**
             * @description Other prisoner’s role code in the non-association
             * @example PERPETRATOR
             * @enum {string}
             */
            secondPrisonerRole: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description Other prisoner’s role description in the non-association
             * @example Perpetrator
             */
            secondPrisonerRoleDescription: string;
            /**
             * @description Reason code why these prisoners should be kept apart
             * @example BULLYING
             * @enum {string}
             */
            reason: "BULLYING" | "GANG_RELATED" | "ORGANISED_CRIME" | "LEGAL_REQUEST" | "THREAT" | "VIOLENCE" | "OTHER";
            /**
             * @description Reason description why these prisoners should be kept apart
             * @example Bullying
             */
            reasonDescription: string;
            /**
             * @description Location-based restriction code
             * @example CELL
             * @enum {string}
             */
            restrictionType: "CELL" | "LANDING" | "WING";
            /**
             * @description Location-based restriction description
             * @example Cell only
             */
            restrictionTypeDescription: string;
            /**
             * @description Explanation of why prisoners are non-associated
             * @example John and Luke always end up fighting
             */
            comment: string;
            /**
             * Format: date-time
             * @description When the non-association was created
             * @example 2021-12-31T12:34:56.789012
             */
            whenCreated: string;
            /**
             * Format: date-time
             * @description When the non-association was last updated
             * @example 2022-01-03T12:34:56.789012
             */
            whenUpdated: string;
            /**
             * @description User ID of the person who last updated the non-association
             * @example OFF3_GEN
             */
            updatedBy: string;
            /**
             * @description Whether the non-association is closed or is in effect
             * @example false
             */
            isClosed: boolean;
            /**
             * @description User ID of the person who closed the non-association. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedBy?: string | null;
            /**
             * @description Reason why the non-association was closed. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedReason?: string | null;
            /**
             * Format: date-time
             * @description Date and time of when the non-association was closed. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedAt?: string | null;
            isOpen: boolean;
        };
        /** @description Request to close a non-association */
        CloseNonAssociationRequest: {
            /**
             * @description Reason for closing the non-association
             * @example They are friends now
             */
            closedReason: string;
            /**
             * Format: date-time
             * @description Date and time of the closure, if not provided will default to today's time
             * @default now
             * @example 2023-06-07
             */
            closedAt: string | null;
            /**
             * @description The username of the member of staff requesting the closure, if not provided will use the user in the JWT access token
             * @example ASMITH
             */
            closedBy?: string | null;
        };
        /** @description Request format for creating a new, open, non-association between two prisoners */
        CreateNonAssociationRequest: {
            /**
             * @description Prisoner number to not associate
             * @example A1234BC
             */
            firstPrisonerNumber: string;
            /**
             * @description This prisoner’s role in the non-association
             * @example VICTIM
             * @enum {string}
             */
            firstPrisonerRole: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description Prisoner number to not associate
             * @example D5678EF
             */
            secondPrisonerNumber: string;
            /**
             * @description Other prisoner’s role in the non-association
             * @example PERPETRATOR
             * @enum {string}
             */
            secondPrisonerRole: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description Reason why these prisoners should be kept apart
             * @example BULLYING
             * @enum {string}
             */
            reason: "BULLYING" | "GANG_RELATED" | "ORGANISED_CRIME" | "LEGAL_REQUEST" | "THREAT" | "VIOLENCE" | "OTHER";
            /**
             * @description Location-based restriction code
             * @example CELL
             * @enum {string}
             */
            restrictionType: "CELL" | "LANDING" | "WING";
            /**
             * @description Explanation of why prisoners are non-associated
             * @example John and Luke always end up fighting
             */
            comment: string;
        };
        /** @description Request to delete a non-association */
        DeleteNonAssociationRequest: {
            /**
             * @description Reason for deleting the non-association
             * @example Created in error and removed on requested from OMU team
             */
            deletionReason: string;
            /**
             * @description The username of the member of staff requesting the deletion
             * @example AJONES
             */
            staffUserNameRequestingDeletion: string;
        };
        /** @description Request format for updating a non-association between two prisoners */
        PatchNonAssociationRequest: {
            /**
             * @description This prisoner’s role in the non-association
             * @example VICTIM
             * @enum {string|null}
             */
            firstPrisonerRole?: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN" | null;
            /**
             * @description Other prisoner’s role in the non-association
             * @example PERPETRATOR
             * @enum {string|null}
             */
            secondPrisonerRole?: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN" | null;
            /**
             * @description Reason why these prisoners should be kept apart
             * @example BULLYING
             * @enum {string|null}
             */
            reason?: "BULLYING" | "GANG_RELATED" | "ORGANISED_CRIME" | "LEGAL_REQUEST" | "THREAT" | "VIOLENCE" | "OTHER" | null;
            /**
             * @description Location-based restriction code
             * @example CELL
             * @enum {string|null}
             */
            restrictionType?: "CELL" | "LANDING" | "WING" | null;
            /**
             * @description Explanation of why prisoners are non-associated
             * @example John and Luke always end up fighting
             */
            comment?: string | null;
        };
        Attachment: {
            /**
             * Format: int32
             * @description The number of the attachment which will match any corresponding reference in the content section
             */
            attachmentNumber: number;
            /** @description The name or description of the attachment which will be included in the report */
            name: string;
            /** @description The content type of the attachment */
            contentType: string;
            /** @description The url to be used to download the attachment file */
            url: string;
            /**
             * Format: int32
             * @description The size of the attachment file in bytes
             */
            filesize?: number | null;
            /** @description The filename of attachment file */
            filename: string;
            /** @description The additional headers to use when calling the url for fetching this attachment */
            headers?: components["schemas"]["AttachmentHeader"][] | null;
        };
        AttachmentHeader: {
            /** @description The name of the header */
            name: string;
            /** @description The value of the header */
            value: string;
        };
        HmppsSubjectAccessRequestContent: {
            /** @description The content of the subject access request response */
            content: unknown;
            /** @description The details of any attachments for the subject access request response */
            attachments?: components["schemas"]["Attachment"][] | null;
        };
        DlqMessage: {
            body: {
                [key: string]: unknown;
            };
            messageId: string;
        };
        GetDlqResult: {
            /** Format: int32 */
            messagesFoundCount: number;
            /** Format: int32 */
            messagesReturnedCount: number;
            messages: components["schemas"]["DlqMessage"][];
        };
        /** @description Other prisoner’s details for an item in a list of non-associations */
        OtherPrisonerDetails: {
            /**
             * @description Prisoner number
             * @example D5678EF
             */
            prisonerNumber: string;
            /**
             * @description Other prisoner’s role code in the non-association
             * @example PERPETRATOR
             * @enum {string}
             */
            role: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description Other prisoner’s role description in the non-association
             * @example Perpetrator
             */
            roleDescription: string;
            /**
             * @description First name
             * @example Joseph
             */
            firstName: string;
            /**
             * @description Last name
             * @example Bloggs
             */
            lastName: string;
            /**
             * @description ID of the prison the prisoner is assigned to
             * @example MDI
             */
            prisonId?: string | null;
            /**
             * @description Name of the prison the prisoner is assigned to
             * @example Moorland (HMP & YOI)
             */
            prisonName?: string | null;
            /**
             * @description Cell the prisoner is assigned to
             * @example B-2-007
             */
            cellLocation?: string | null;
        };
        /** @description An item in a list of non-associations for a given prisoner */
        PrisonerNonAssociation: {
            /**
             * Format: int64
             * @description ID of the non-association
             * @example 42
             */
            id: number;
            /**
             * @description This prisoner’s role code in the non-association
             * @example VICTIM
             * @enum {string}
             */
            role: "VICTIM" | "PERPETRATOR" | "NOT_RELEVANT" | "UNKNOWN";
            /**
             * @description This prisoner’s role description in the non-association
             * @example Victim
             */
            roleDescription: string;
            /**
             * @description Reason code why these prisoners should be kept apart
             * @example BULLYING
             * @enum {string}
             */
            reason: "BULLYING" | "GANG_RELATED" | "ORGANISED_CRIME" | "LEGAL_REQUEST" | "THREAT" | "VIOLENCE" | "OTHER";
            /**
             * @description Reason description why these prisoners should be kept apart
             * @example Bullying
             */
            reasonDescription: string;
            /**
             * @description Location-based restriction code
             * @example CELL
             * @enum {string}
             */
            restrictionType: "CELL" | "LANDING" | "WING";
            /**
             * @description Location-based restriction description
             * @example Cell only
             */
            restrictionTypeDescription: string;
            /**
             * @description Explanation of why prisoners are non-associated
             * @example John and Luke always end up fighting
             */
            comment: string;
            /**
             * @description User ID of the person who created the non-association. NOTE: For records migrated from NOMIS/Prison API this is free text and may not be a valid User ID. Additionally, migrated records might use an internal system username. It can be an empty string
             * @example OFF3_GEN
             */
            authorisedBy: string;
            /**
             * Format: date-time
             * @description When the non-association was created
             * @example 2021-12-31T12:34:56.789012
             */
            whenCreated: string;
            /**
             * Format: date-time
             * @description When the non-association was last updated
             * @example 2022-01-03T12:34:56.789012
             */
            whenUpdated: string;
            /**
             * @description User ID of the person who last updated the non-association
             * @example OFF3_GEN
             */
            updatedBy: string;
            /**
             * @description Whether the non-association is closed or is in effect
             * @example false
             */
            isClosed: boolean;
            /**
             * @description User ID of the person who closed the non-association. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedBy?: string | null;
            /**
             * @description Reason why the non-association was closed. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedReason?: string | null;
            /**
             * Format: date-time
             * @description Date and time of when the non-association was closed. Only present when the non-association is closed, null for open non-associations
             * @example null
             */
            closedAt?: string | null;
            /** @description Details about the other person in the non-association. */
            otherPrisonerDetails: components["schemas"]["OtherPrisonerDetails"];
            isOpen: boolean;
        };
        /** @description List of non-associations for a given prisoner */
        PrisonerNonAssociations: {
            /**
             * @description Prisoner number
             * @example A1234BC
             */
            prisonerNumber: string;
            /**
             * @description First name
             * @example James
             */
            firstName: string;
            /**
             * @description Last name
             * @example Hall
             */
            lastName: string;
            /**
             * @description ID of the prison the prisoner is assigned to
             * @example MDI
             */
            prisonId?: string | null;
            /**
             * @description Name of the prison the prisoner is assigned to
             * @example Moorland (HMP & YOI)
             */
            prisonName?: string | null;
            /**
             * @description Cell the prisoner is assigned to
             * @example A-1-002
             */
            cellLocation?: string | null;
            /**
             * Format: int32
             * @description Number of open non-associations (follows includeOtherPrisons filter)
             * @example 1
             */
            openCount: string;
            /**
             * Format: int32
             * @description Number of closed non-associations (follows includeOtherPrisons filter)
             * @example 0
             */
            closedCount: string;
            /** @description Non-associations with other prisoners */
            nonAssociations: components["schemas"]["PrisonerNonAssociation"][];
        };
        PageNonAssociation: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["NonAssociation"][];
            /** Format: int32 */
            number?: number;
            first?: boolean;
            last?: boolean;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
            paged?: boolean;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        /** @description Non-association in NOMIS/Prison API format */
        LegacyNonAssociation: {
            /**
             * Format: int64
             * @description ID of the non-association
             * @example 42
             */
            id: number;
            /**
             * @description Prisoner number
             * @example A1234BC
             */
            offenderNo: string;
            /**
             * @description Reason code for the non-association
             * @example VIC
             * @enum {string}
             */
            reasonCode: "BUL" | "PER" | "RIV" | "VIC" | "NOT_REL" | "UNKNOWN";
            /**
             * @description Reason for the non-association
             * @example Victim
             */
            reasonDescription: string;
            /**
             * @description The non-association type code
             * @example WING
             * @enum {string}
             */
            typeCode: "CELL" | "LAND" | "WING";
            /**
             * @description The non-association type description
             * @example Do Not Locate on Same Wing
             */
            typeDescription: string;
            /**
             * Format: date-time
             * @description Date and time the non-association is effective from. In Europe/London (ISO 8601) format without timezone offset e.g. YYYY-MM-DDTHH:MM:SS.
             * @example 2021-07-05T00:00:00
             */
            effectiveDate: string;
            /**
             * Format: date-time
             * @description Date and time the non-association expires. In Europe/London (ISO 8601) format without timezone offset e.g. YYYY-MM-DDTHH:MM:SS.
             * @example 2021-07-05T00:00:00
             */
            expiryDate?: string | null;
            /**
             * @description The person who authorised the non-association (free text).
             * @example Officer Alice B.
             */
            authorisedBy?: string | null;
            /**
             * @description Additional free text comments related to the non-association.
             * @example Mr. Bloggs assaulted Mr. Hall
             */
            comments: string;
            /** @description Details about the other non-association person */
            offenderNonAssociation: components["schemas"]["LegacyNonAssociationOtherPrisonerDetails"];
        };
        /** @description Details about the other non-association person in NOMIS/Prison API format */
        LegacyNonAssociationOtherPrisonerDetails: {
            /**
             * @description Prisoner number
             * @example B1234CD
             */
            offenderNo: string;
            /**
             * @description Reason code for the non-association
             * @example PER
             * @enum {string}
             */
            reasonCode: "BUL" | "PER" | "RIV" | "VIC" | "NOT_REL" | "UNKNOWN";
            /**
             * @description Reason for the non-association
             * @example Perpetrator
             */
            reasonDescription: string;
        };
        Constant: {
            code: string;
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retryDlq: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dlqName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetryDlqResult"];
                };
            };
        };
    };
    retryAllDlqs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RetryDlqResult"][];
                };
            };
        };
    };
    purgeQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queueName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurgeQueueResult"];
                };
            };
        };
    };
    reopenNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenNonAssociationRequest"];
            };
        };
        responses: {
            /** @description Non-association re-opened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the REOPEN_NON_ASSOCIATIONS role with write scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    closeNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseNonAssociationRequest"];
            };
        };
        responses: {
            /** @description Non-association updated and returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role with write scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNonAssociations: {
        parameters: {
            query?: {
                /**
                 * @description Whether to include open non-associations or not
                 * @example false
                 */
                includeOpen?: boolean;
                /**
                 * @description Whether to include closed non-associations or not
                 * @example true
                 */
                includeClosed?: boolean;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of non-associations are returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageNonAssociation"];
                };
            };
            /** @description When input parameters are not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the READ_NON_ASSOCIATIONS role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNonAssociationRequest"];
            };
        };
        responses: {
            /** @description Returns the created non-association */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required privileges. Requires the NON_ASSOCIATIONS role with write scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Some of the prisoners were not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Open non-association already exists or some prisoner’s location is null. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteNonAssociationRequest"];
            };
        };
        responses: {
            /** @description Non-association deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the DELETE_NON_ASSOCIATIONS role with write scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNonAssociationsInvolvingPrisoners: {
        parameters: {
            query?: {
                /**
                 * @description Whether to include open non-associations or not
                 * @example false
                 */
                includeOpen?: boolean;
                /**
                 * @description Whether to include closed non-associations or not
                 * @example true
                 */
                includeClosed?: boolean;
                /**
                 * @description When provided return only non-associations where both prisoners are in the given prison
                 * @example MDI
                 */
                prisonId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Returns the non-associations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"][];
                };
            };
            /** @description When fewer than one distinct prisoner numbers are provided or neither open nor closed non-associations are included */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Any of the prisoners could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNonAssociationsBetweenPrisoners: {
        parameters: {
            query?: {
                /**
                 * @description Whether to include open non-associations or not
                 * @example false
                 */
                includeOpen?: boolean;
                /**
                 * @description Whether to include closed non-associations or not
                 * @example true
                 */
                includeClosed?: boolean;
                /**
                 * @description When provided return only non-associations where both prisoners are in the given prison
                 * @example MDI
                 */
                prisonId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Returns the non-associations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"][];
                };
            };
            /** @description When fewer than two distinct prisoner numbers are provided or neither open nor closed non-associations are included */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Any of the prisoners could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the non-association */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patchNonAssociation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchNonAssociationRequest"];
            };
        };
        responses: {
            /** @description Non-association updated and returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NonAssociation"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role with write scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSarContentByReference: {
        parameters: {
            query?: {
                /** @description NOMIS Prison Reference Number */
                prn?: string;
                /** @description nDelius Case Reference Number */
                crn?: string;
                /** @description Optional parameter denoting minimum date of event occurrence which should be returned in the response */
                fromDate?: string;
                /** @description Optional parameter denoting maximum date of event occurrence which should be returned in the response */
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request successfully processed - content found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HmppsSubjectAccessRequestContent"];
                };
            };
            /** @description Request successfully processed - no content found */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Subject Identifier is not recognised by this service */
            209: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description The client does not have authorisation to make this request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden, requires an appropriate role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDlqMessages: {
        parameters: {
            query?: {
                maxMessages?: number;
            };
            header?: never;
            path: {
                dlqName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetDlqResult"];
                };
            };
        };
    };
    getPrisonerNonAssociations: {
        parameters: {
            query?: {
                /**
                 * @description Whether to include open non-associations or not
                 * @example false
                 */
                includeOpen?: boolean;
                /**
                 * @description Whether to include closed non-associations or not
                 * @example true
                 */
                includeClosed?: boolean;
                /**
                 * @description Whether to include non-associations with prisoners in other prisons
                 * @example true
                 */
                includeOtherPrisons?: boolean;
                /**
                 * @description Sort non-associations by
                 * @example LAST_NAME
                 */
                sortBy?: "WHEN_CREATED" | "WHEN_UPDATED" | "WHEN_CLOSED" | "LAST_NAME" | "FIRST_NAME" | "PRISONER_NUMBER" | "PRISON_ID" | "PRISON_NAME" | "CELL_LOCATION" | "WHEN_CREATED" | "WHEN_UPDATED" | "WHEN_CLOSED" | "LAST_NAME" | "FIRST_NAME" | "PRISONER_NUMBER" | "PRISON_ID" | "PRISON_NAME" | "CELL_LOCATION";
                /**
                 * @description Sort direction (fallback depends on sortBy)
                 * @example DESC
                 */
                sortDirection?: "ASC" | "DESC" | "ASC" | "DESC";
            };
            header?: never;
            path: {
                /**
                 * @description The prisoner number
                 * @example A1234BC
                 */
                prisonerNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns non-association details for this prisoner */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrisonerNonAssociations"];
                };
            };
            /** @description Bad request; for example including neither open nor closed non-associations */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Any of the prisoners could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLegacyById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The non-association ID
                 * @example 42
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the non-association */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyNonAssociation"];
                };
            };
            /** @description Unauthorized to access this endpoint */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing required role. Requires the NON_ASSOCIATIONS_SYNC role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non-association not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    constants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns codes and descriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Constant"][];
                    };
                };
            };
        };
    };
}
